# Generated by Django 6.0.6 on 2026-06-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(help_text='Número ou identificação da prateleira ou armário.', unique=True, verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Armário',
                'verbose_name_plural': 'Armários',
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='GHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Descrição do perigo GHS (ex.: Inflamável, Corrosivo).', max_length=100, verbose_name='Nome')),
                ('picto', models.CharField(help_text='Caminho ou nome do arquivo do pictograma GHS.', max_length=255, verbose_name='Pictograma')),
            ],
            options={
                'verbose_name': 'GHS',
                'verbose_name_plural': 'GHS',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reagente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do reagente químico.', max_length=200, verbose_name='Nome')),
                ('cas', models.CharField(help_text='Número CAS (Chemical Abstracts Service) da substância.', max_length=50, verbose_name='CAS')),
                ('ghs', models.ForeignKey(help_text='Classificação de perigo GHS associada ao reagente.', on_delete=django.db.models.deletion.PROTECT, related_name='reagentes', to='estoque.ghs', verbose_name='Classificação GHS')),
            ],
            options={
                'verbose_name': 'Reagente',
                'verbose_name_plural': 'Reagentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(help_text='Identificação do lote de fabricação.', max_length=100, verbose_name='Lote')),
                ('validade', models.DateField(help_text='Data de validade do frasco.', verbose_name='Validade')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Volume ou massa disponível no frasco.', max_digits=10, verbose_name='Quantidade')),
                ('qtd_unidade', models.CharField(help_text='Unidade de medida da quantidade (ex.: ml, g, L).', max_length=20, verbose_name='Unidade da quantidade')),
                ('concentracao', models.DecimalField(decimal_places=4, help_text='Concentração deste frasco específico.', max_digits=10, verbose_name='Concentração')),
                ('conc_unidade', models.CharField(help_text='Unidade da concentração (ex.: %, M, N).', max_length=20, verbose_name='Unidade da concentração')),
                ('fornecedor', models.CharField(help_text='Nome do fornecedor do frasco.', max_length=200, verbose_name='Fornecedor')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras do frasco, se houver.', max_length=100, verbose_name='Código de barras')),
                ('armario', models.ForeignKey(help_text='Localização física (prateleira/armário) do frasco.', on_delete=django.db.models.deletion.PROTECT, related_name='itens_estoque', to='estoque.armario', verbose_name='Armário')),
                ('reagente', models.ForeignKey(help_text='Reagente do catálogo ao qual este frasco pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='itens_estoque', to='estoque.reagente', verbose_name='Reagente')),
            ],
            options={
                'verbose_name': 'Item de estoque',
                'verbose_name_plural': 'Itens de estoque',
                'ordering': ['reagente__nome', 'validade'],
            },
        ),
    ]
