# Generated by Django 6.0.6 on 2026-06-13 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída'), ('Consumo', 'Consumo'), ('Descarte', 'Descarte')], help_text='Natureza da movimentação (entrada, saída, consumo ou descarte).', max_length=20, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade movimentada na operação.', max_digits=10, verbose_name='Quantidade')),
                ('data_hora', models.DateTimeField(auto_now_add=True, help_text='Momento em que a movimentação foi registrada.', verbose_name='Data e hora')),
                ('justificativa', models.CharField(blank=True, help_text='Observação opcional (ex.: Quebra de frasco, Preparação de aula prática).', max_length=255, verbose_name='Justificativa')),
                ('item_estoque', models.ForeignKey(help_text='Frasco físico afetado pela movimentação.', on_delete=django.db.models.deletion.CASCADE, related_name='historico_movimentacoes', to='estoque.itemestoque', verbose_name='Item de estoque')),
                ('usuario', models.ForeignKey(help_text='Usuário responsável pela alteração.', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de movimentação',
                'verbose_name_plural': 'Históricos de movimentação',
                'ordering': ['-data_hora'],
            },
        ),
    ]
