# Generated by Django 6.0.6 on 2026-07-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_reagente_classificacoes_ghs_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagente',
            name='fds_url',
            field=models.URLField(blank=True, help_text='URL do PDF da Ficha de Dados de Segurança (FDS/FISPQ) do fabricante.', null=True, verbose_name='Link da FDS/FISPQ'),
        ),
    ]
