# Generated by Django 6.0.6 on 2026-07-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_reagente_fds_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimentacao',
            name='unidade',
            field=models.CharField(choices=[('L', 'L (Litros)'), ('mL', 'mL (Mililitros)'), ('kg', 'kg (Quilogramas)'), ('g', 'g (Gramas)')], default='mL', help_text='Unidade em que a quantidade foi informada (pode diferir da unidade do frasco).', max_length=5, verbose_name='Unidade'),
        ),
    ]
