# Generated by Django 6.0.6 on 2026-09-05 15:14

from django.db import migrations

CODENAMES_ESCRITA = (
    'add_historicomovimentacao',
    'change_historicomovimentacao',
    'delete_historicomovimentacao',
    'add_itemestoque',
    'change_itemestoque',
    'delete_itemestoque',
    'add_reagente',
    'change_reagente',
    'delete_reagente',
    'add_armario',
    'change_armario',
    'delete_armario',
    'add_ghs',
    'change_ghs',
    'delete_ghs',
    'pode_movimentar_estoque',
)


def restringir_grupo_alunos(apps, schema_editor):
    """Garante que o grupo Alunos não tenha permissões de escrita no estoque."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    alunos = Group.objects.filter(name='Alunos').first()
    if alunos is None:
        return

    perms = Permission.objects.filter(codename__in=CODENAMES_ESCRITA)
    alunos.permissions.remove(*perms)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_historico_unidade'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicomovimentacao',
            options={
                'ordering': ['-data_hora'],
                'permissions': [
                    (
                        'pode_movimentar_estoque',
                        'Pode registrar movimentações de estoque (entrada, saída, consumo e descarte)',
                    )
                ],
                'verbose_name': 'Histórico de movimentação',
                'verbose_name_plural': 'Históricos de movimentação',
            },
        ),
        migrations.RunPython(restringir_grupo_alunos, noop),
    ]
